---
roles:
  - name: nephelaiio.ubuntu_installer
  - name: nephelaiio.debian_installer
  - name: nephelaiio.centos_installer
collections:
  - community.general
  - nephelaiio.plugins
  - nephelaiio.libvirt
