---
- name: Set variable overrides
  ansible.builtin.set_fact:
    _growfs_packages: "{{ growfs_packages | default(growfs_packages_default | nephelaiio.plugins.sorted_get(overrides)) }}"
    _growfs_lvs_fs: "{{ growfs_fs | default(growfs_fs_default) | nephelaiio.plugins.sorted_get(overrides) }}"
  vars:
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"
  tags: always

- name: Ensure device filter is set
  ansible.builtin.fail:
    msg: growfs_device_filter must be set
  when: growfs_device_filter is not defined

- name: Install required packages
  ansible.builtin.package:
    name: "{{ _growfs_packages }}"
    state: present

- name: Query existing lvm vg
  ansible.builtin.command: "vgs --reportformat json --nosuffix"
  register: vgs_query
  changed_when: false

- name: Query existing lvm lvs
  ansible.builtin.command: "lvs --reportformat json --nosuffix"
  register: lvs_query
  changed_when: false

- name: Query existing lvm pvs
  ansible.builtin.command: "pvs --reportformat json --nosuffix"
  register: pvs_query
  changed_when: false

- name: Determine lsblk syntax
  ansible.builtin.command: lsblk --help
  register: lsblk_command_help
  tags: skip_ansible_lint

- name: Register lvm facts
  ansible.builtin.set_fact:
    lvm_vgs: "{{ (vgs_query.stdout | from_json).report | map(attribute='vg') | flatten }}"
    lvm_lvs: "{{ (lvs_query.stdout | from_json).report | map(attribute='lv') | flatten }}"
    lvm_pvs: "{{ (pvs_query.stdout | from_json).report | map(attribute='pv') | flatten }}"

- name: Include static partitioning tasks
  ansible.builtin.include_tasks: "static.yml"
  when: lvm_vgs | length == 0

- name: Include lvm partitioning tasks
  ansible.builtin.include_tasks: "lvm.yml"
  when: lvm_vgs | length > 0
