---
- name: set debug environment

  hosts: molecule

  vars_files:
    - ./vars.yml

  tasks:

    - name: debug ec2 instance info
      debug:
        msg: "{{ ansible_user_id }}@{{ ansible_host }}"
      become: no

    - name: debug guest instance credentials
      debug:
        msg: "user={{ molecule_username }}, password={{ molecule_password }}"

    - name: add debug ssh key
      authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "{{ debug_pubkey }}"
      become: no


- name: build kvm guest installers

  hosts: molecule

  become: yes

  vars_files:
    - ./vars.yml

  pre_tasks:

    - name: update apt package cache
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'

    - name: install disk utils
      apt:
        name:
          - parted
          - lvm2

    - name: select EC2 NVMe disks
      set_fact:
        ec2_disks: "{{ ec2_disks | default([]) + [ec2_disk] }}"
      vars:
        ec2_disk: "/dev/{{ item.key }}"
      when:
        - item.value.model == 'Amazon EC2 NVMe Instance Storage'
      loop_control:
        label: "{{ item.key }}"
      loop: "{{ ansible_devices | dict2items }}"

    - block:

        - name: create molecule vg
          lvg:
            vg: molecule
            pvs: "{{ ','.join(ec2_disks) }}"

        - name: create molecule lv
          lvol:
            vg: molecule
            lv: molecule
            size: "+100%FREE"

        - name: create molecule filesystem
          filesystem:
            fstype: ext4
            dev: /dev/mapper/molecule-molecule

        - name: mount molecule filesystem
          mount:
            path: "{{ cache_dir }}"
            src: /dev/mapper/molecule-molecule
            fstype: ext4
            state: mounted
      when:
        - ec2_disks is defined
        - (ec2_disks | length) > 0

  tasks:

    - name: cache installer files
      get_url:
        url: "{{ iso.value.url }}"
        dest: "{{ iso.value.dest | urlsplit('path') }}"
      loop_control:
        loop_var: iso
        label: "{{ iso.key }}"
      loop: "{{ iso_installers | dict2items }}"

    - name: build ubuntu guest installer isos
      include_role:
        name: nephelaiio.ubuntu_installer
      vars:
        ubuntu_installer_interface_name: enp0s3
        ubuntu_installer_target_dir: "{{ cache_dir }}"
        ubuntu_installer_image_url: "{{ iso_installers[guest.installer_ref].dest }}"
        ubuntu_installer_hostname: "{{ guest.installer_hostname }}"
        ubuntu_installer_username: "{{ molecule_username }}"
        ubuntu_installer_password: "{{ molecule_password | password_hash('sha512') }}"
        ubuntu_installer_sshkey:
          - "{{ lookup('file', kvm_key_pair_path + '.pub') }}"
          - "{{ debug_pubkey }}"
        ubuntu_installer_halt: false
        ubuntu_installer_interface: "{{ guest.installer_interface }}"
        ubuntu_installer_partman_method: "{{ guest.installer_partitioning_method }}"
        ubuntu_installer_mirror: "{{ guest.installer_mirror | default('archive.ubuntu.com') }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"
      when: guest.installer_type == 'ubuntu'

    - name: build centos guest installer isos
      include_role:
        name: nephelaiio.centos_installer
      vars:
        centos_installer_interface_name: enp0s3
        centos_installer_target_dir: "{{ cache_dir }}"
        centos_installer_image_url: "{{ iso_installers[guest.installer_ref].dest }}"
        centos_installer_hostname: "{{ guest.installer_hostname }}"
        centos_installer_username: "{{ molecule_username }}"
        centos_installer_password: "{{ molecule_password | password_hash('sha512') }}"
        centos_installer_root_password: "{{ molecule_password | password_hash('sha512') }}"
        centos_installer_baseurl: "{{ base_url | default('') }}"
        centos_installer_sshkey:
          - "{{ lookup('file', kvm_key_pair_path + '.pub') }}"
          - "{{ debug_pubkey }}"
        centos_installer_halt: false
        centos_installer_interface: "{{ guest.installer_interface }}"
        centos_installer_ks_partitioning: "{{ guest.installer_ks_partitioning }}"
        centos_installer_ks_template: "{{ guest.installer_ks_template }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"
      when: guest.installer_type == 'centos'


- import_playbook: inventory.yml


- name: create guests

  hosts: molecule

  gather_facts: no

  become: yes

  vars_files:
    - ./vars.yml

  tasks:

    - name: destroy kvm guest
      virt:
        command: destroy
        name: "{{ guest.installer_hostname }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"
      failed_when: false

    - name: undefine kvm guest
      virt:
        command: undefine
        name: "{{ guest.installer_hostname }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"
      failed_when: false

    - name: destroy kvm guest disks
      file:
        path: "{{ guest_disk }}"
        state: absent
      vars:
        guest_disk: "{{ cache_dir }}/{{ guest.installer_hostname }}.img"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"

    - name: create kvm guest disks
      command: "qemu-img create {{ guest_disk }} {{ guest_disk_size }}"
      args:
        creates: "{{ guest_disk }}"
      vars:
        guest_disk: "{{ cache_dir }}/{{ guest.installer_hostname }}.img"
        guest_disk_size: "{{ guest.installer_disk_size }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"

    - name: manage permissions for kvm guest disks
      file:
        path: "{{ guest_disk }}"
        owner: libvirt-qemu
        group: kvm
        mode: 0640
      vars:
        guest_disk: "{{ cache_dir }}/{{ guest.installer_hostname }}.img"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"

    - name: create kvm guest
      virt:
        xml: "{{ xml_template }}"
        command: define
      vars:
        guest_hostname: "{{ guest.installer_hostname }}"
        guest_bridge: "{{ bridge_name }}"
        guest_iso: "{{ cache_dir }}/{{ guest_hostname }}.iso"
        guest_disk_path: "{{ cache_dir }}/{{ guest.installer_hostname }}.img"
        guest_mac: "{{ '52:54:00' | random_mac(seed=guest_hostname)}}"
        guest_disk_format: raw
        xml_template: "{{ lookup('template', 'vm.xml.j2') }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"

    - name: start kvm guest
      virt:
        name: "{{ guest_hostname }}"
        state: running
      vars:
        guest_hostname: "{{ guest.installer_hostname }}"
      loop_control:
        loop_var: guest
        label: "{{ guest.installer_hostname }}"
      loop: "{{ guests }}"


- name: wait for guest startup

  hosts: guests

  gather_facts: no

  vars_files:
    - ./vars.yml

  pre_tasks:

    - name: wait for connection
      wait_for_connection:
        timeout: 1800

    - name: wait for cloud-init to complete
      pause:
        minutes: 2
