---
- name: Add guests to inventory
  hosts: localhost
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Add guest to inventory
      ansible.builtin.add_host:
        name: "{{ guest_hostname }}"
        groups:
          - guests
        ansible_user: molecule
        ansible_host: "{{ guest_address }}"
        ansible_port: "{{ guest_port }}"
        ansible_ssh_private_key_file: "{{ _libvirt_keypair }}"
        partitioning_method: "{{ guest.installer_partitioning_method }}"
        disk_location: "{{ _libvirt_path }}/{{ guest.installer_hostname }}.img"
        disk_size: "{{ guest.installer_disk_size }}"
        disk_index: "{{ disk_index }}"
      vars:
        guest_hostname: "{{ guest.installer_hostname }}"
        guest_address: "{{ guest.installer_interface.ipaddress }}"
        guest_port: 22
      loop_control:
        loop_var: guest
        index_var: disk_index
        label: "{{ guest.installer_hostname }}"
      loop: "{{ molecule_kvm_guests }}"
