---
- name: Prepare KVM host
  ansible.builtin.import_playbook: nephelaiio.libvirt.prepare

- name: Create KVM guest installer isos
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create KVM keypair
      ansible.builtin.command:
        cmd: "ssh-keygen -t rsa -f {{ libvirt_privkey }} -q -P '' -C ''"
        creates: "{{ libvirt_privkey }}"

    - name: Cache installer iso
      ansible.builtin.get_url:
        url: "{{ molecule_installer_url }}"
        dest: "{{ libvirt_path }}/{{ molecule_distro }}.iso"

    - name: Build OS installer isos
      become: true
      block:
        - name: Build ubuntu installer isos
          ansible.builtin.include_role:
            name: nephelaiio.ubuntu_installer
          vars:
            ubuntu_guest: "{{ hostvars[item] }}"
            ubuntu_installer_interface_name: enp1s0
            ubuntu_installer_target_dir: "{{ libvirt_path }}"
            ubuntu_installer_image_url: "file://{{ libvirt_path }}/{{ molecule_distro }}.iso"
            ubuntu_installer_hostname: "{{ item }}"
            ubuntu_installer_username: molecule
            ubuntu_installer_password: "{{ 'molecule' | password_hash('sha512') }}"
            ubuntu_installer_sshkey:
              - "{{ lookup('file', libvirt_privkey + '.pub') }}"
            ubuntu_installer_interface: "{{ ubuntu_guest.installer_interface }}"
            ubuntu_installer_partman_method: "{{ ubuntu_guest.partitioning_method }}"
          loop: "{{ libvirt_platforms | map(attribute='name') }}"
          when: molecule_scenario != "debian"

        - name: Build debian installer isos
          ansible.builtin.include_role:
            name: nephelaiio.debian_installer
          vars:
            debian_guest: "{{ hostvars[item] }}"
            debian_installer_interface_name: enp1s0
            debian_installer_target_dir: "{{ _libvirt_path }}"
            debian_installer_image_url: "file://{{ libvirt_path }}/{{ molecule_distro }}.iso"
            debian_installer_hostname: "{{ item }}"
            debian_installer_username: molecule
            debian_installer_password: "{{ 'molecule' | password_hash('sha512') }}"
            debian_installer_sshkey:
              - "{{ lookup('file', libvirt_privkey + '.pub') }}"
            debian_installer_interface: "{{ debian_guest.installer_interface }}"
            debian_installer_partman_method: "{{ debian_guest.partitioning_method }}"
            debian_installer_preseed_include: "{{ debian_guest.preseed_include | default('') }}"
          loop: "{{ libvirt_platforms | map(attribute='name') }}"
          when: molecule_scenario == "debian"
