---
- name: Build dynamic inventory
  ansible.builtin.import_playbook: inventory.yml


- name: Reboot guest
  hosts: guests
  become: true
  pre_tasks:

    - name: Shut down guest
      community.general.shutdown:

    - name: Wait for shutdown to complete
      ansible.builtin.pause:
        seconds: 30

  tasks:
    - name: Start guests
      delegate_to: localhost
      block:

        - name: Force kvm guest poweroff
          ansible.builtin.shell: "virsh destroy {{ inventory_hostname }} >/dev/null 2>&1"
          tags: skip_ansible_lint
          ignore_errors: true
          failed_when: false
          changed_when: false

        - name: Wait for kvm guest poweroff
          ansible.builtin.pause:
            minutes: 2

        - name: Start kvm guest
          community.libvirt.virt:
            name: "{{ inventory_hostname }}"
            state: running

    - name: Wait for connection
      ansible.builtin.wait_for_connection:
