---
_libvirt_network: "{{ molecule_libvirt_network | default(_project_name) }}"
_libvirt_address: "{{ molecule_libvirt_address | default('172.31.255.1/24') }}"
_libvirt_user: "{{ molecule_libvirt_user | default('molecule') }}"
_libvirt_pool: "{{ molecule_libvirt_pool | default(_project_name) }}"
_libvirt_path: "{{ molecule_libvirt_path | default(_project_pool) }}"
_libvirt_keypair: "{{ _libvirt_path }}/id_rsa"
_libvirt_daemon_user: "{{ _daemon_user }}"
_libvirt_daemon_group: "{{ _daemon_user }}"

_daemon_user: "{{ (ansible_os_family == 'Debian') | ternary('libvirt-qemu', _project_user) }}"
_project_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
_project_temp: "{{ lookup('ansible.builtin.env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}"
_project_path: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
_project_name: "{{ _project_path | basename | replace('_', '-') | replace('.', '-') }}"
_project_pool: "{{ _project_path }}/libvirt/{{ _project_name }}"
