---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: default
platforms:
  - name: growfs-ubuntu-lvm-10g
  - name: growfs-ubuntu-static-10g
provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_VERBOSITY:-0}
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: ansible.posix.profile_tasks
      callback_whitelist: profile_tasks, timer, yaml
  playbooks:
    prepare: ../common/prepare.yml
    create: ../common/create.yml
    converge: ../common/converge.yml
    verify: ../common/verify.yml
    destroy: ../common/destroy.yml
    side_effect: ../common/reboot.yml
  inventory:
    group_vars:
      all:
        libvirt_network: "nephelaiio-growfs"
        libvirt_platforms: "{{ molecule_yml.platforms }}"
        libvirt_address: "172.31.249.1/24"
        libvirt_path: "{{ molecule_project }}/libvirt/nephelaiio-growfs"
        libvirt_privkey: "{{ libvirt_path }}/id_rsa"
        libvirt_disk_size: "{{ 10*(1024**3) }}"
        libvirt_nameservers:
          - 1.1.1.1
          - 8.8.8.8

        growfs_device_filter: "vd.*"
        molecule_scenario: "${MOLECULE_SCENARIO_NAME}"
        molecule_distro: "{{ lookup('env', 'MOLECULE_DISTRO') }}"
        molecule_installer_url: "{{ lookup('env', 'MOLECULE_ISO') }}"
        molecule_install_dir: "{{ lookup('env', 'MOLECULE_OUTPUT_DIR', default='/tmp/logs') }}"
        molecule_network: "{{ libvirt_address | ansible.utils.ipaddr('network') }}"
        molecule_netmask: "{{ libvirt_address | ansible.utils.ipaddr('netmask') }}"
        molecule_prefix: "{{ libvirt_address | ansible.utils.ipaddr('prefix') }}"
        molecule_netaddr: "{{ molecule_network }}/{{ molecule_prefix }}"
        molecule_project: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"

    host_vars:
      growfs-ubuntu-lvm-10g:
        libvirt_guest_address: "{{ molecule_netaddr | ansible.utils.nthhost(2) }}"
        libvirt_guest_iso: "{{ libvirt_path }}/{{ inventory_hostname }}.iso"
        partitioning_method: lvm
        installer_interface:
          static: true
          ipaddress: "{{ libvirt_guest_address }}"
          network: "{{ molecule_network }}"
          netmask: "{{ molecule_netmask }}"
          gateway: "{{ libvirt_address | ansible.utils.ipaddr('address') }}"
          nameservers: "{{ libvirt_nameservers }}"

      growfs-ubuntu-static-10g:
        libvirt_guest_address: "{{ molecule_netaddr | ansible.utils.nthhost(3) }}"
        libvirt_guest_iso: "{{ libvirt_path }}/{{ inventory_hostname }}.iso"
        partitioning_method: regular
        installer_interface:
          static: true
          ipaddress: "{{ libvirt_guest_address }}"
          network: "{{ molecule_network }}"
          netmask: "{{ molecule_netmask }}"
          gateway: "{{ libvirt_address | ansible.utils.ipaddr('address') }}"
          nameservers: "{{ libvirt_nameservers }}"

verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
  prepare_sequence:
    - dependency
    - prepare
  converge_sequence:
    - dependency
    - converge
  verify_sequence:
    - dependency
    - verify
  test_sequence:
    - dependency
    - prepare
    - create
    - converge
    - side_effect
    - verify
