---
name: Mirror

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: 'nephelaiio.growfs'

jobs:

  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.growfs'

      - name: Test debian mirror access (http)
        run: curl http://debian-archive.trafficmanager.net/debian

      - name: Test debian mirror access (https)
        run: curl https://debian-archive.trafficmanager.net/debian

      - name: Test debian security mirror access (http)
        run: curl http://debian-archive.trafficmanager.net/debian-security

      - name: Test debian security mirror access (https)
        run: curl https://debian-archive.trafficmanager.net/debian-security
