---
name: molecule

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  molecule:
    name: molecule
    runs-on: libvirt
    strategy:
      matrix:
        include:
          - scenario: ubuntu
            release: jammy
          - scenario: debian
            release: bullseye
          - scenario: debian
            release: bookworm
          - scenario: absolute
            release: bookworm
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true

      - name: Disable firewall
        run: sudo ufw disable

      - name: run molecule tests
        run: devbox run -- make test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
          MOLECULE_DISTRO: "${{ matrix.release }}"
          MOLECULE_OUTPUT_DIR: "/tmp/logs"

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install.${{ matrix.release }}
          path: |
            /tmp/logs/*.png
            /tmp/logs/*.log
          if-no-files-found: ignore
        if: always()
