---
name: release

on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: "nephelaiio.growfs"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.growfs"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true

      - name: Release collection
        run: devbox run -- make publish
        env:
          GALAXY_API_KEY: "${{ secrets.GALAXY_API_KEY }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
